### PR TITLE
[DEID-2628] Add file type support for pptx and dcm

### PR DESCRIPTION
**Pull request by yuya-kitani**
### What's Changed?

- To add pptx(and ppt), dcm in valid_content_types.
- This PR derived from the conversation in https://github.com/privateai/redocly-docs/pull/328#discussion_r1648972329

### PR Checklist
- [x] Add integration tests
- [x] Ran tests

### CODE REVIEW

**Review by a-guiducci — APPROVED** [review]
Looks good! 🚀

**Review by a-guiducci — CHANGES_REQUESTED** [review]
Sorry @yuya-kitani 1 more thing before merging! Can you update the changelog real quick 🙏

**Review by a-guiducci — APPROVED** [review]
perfect, thanks @yuya-kitani!

**Comment by yuya-kitani** [comment]
> perfect, thanks @yuya-kitani!

Thank you for the review @a-guiducci !

**Pull request merged**
